### ISSUE TITLE
Tmuxinator integration

### ISSUE THREAD

**Issue by lcensies** [omerxx/tmux-sessionx#56]
## Description

There is a number of tmux session managers like [tmuxinator](https://github.com/tmuxinator/tmuxinator) or [tmuxp](https://github.com/tmux-python/tmuxp) that allow you to open a session defined in yaml format .
```yaml
# ~/.tmuxinator/project.yml
windows:
  - editor:
      layout: main-vertical
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - vim
        - guard
  - server: bundle exec rails s
  - logs: tail -f log/development.log
```

While tmux-sessionx is the most convinient session manager I have seen so far, for projects with predefined layouts I firstly have to create a session in shell as follows: 
```bash
alias tx="tmuxinator"
tx project
```

and only then use tmux-sessionx for switching. 

## Proposal

It would be awesome to have integration with any of these tools with option such as
```bash
set -g @sessionx-tmuxinator-mode 'on'

```
so that tmux-sessionx will include available predefined sessions for creation/switching
